name: av-decoders

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run rustfmt
        run: |
          cargo fmt -- --check

  build:
    needs: [rustfmt]
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/setup-nasm@v1

      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2

      - name: No additional features
        run: |
          cargo clippy --tests --benches -- -D warnings
          cargo test

      # - name: With vapoursynth
      #   run: |
      #     cargo clippy --features vapoursynth --tests --benches -- -D warnings
      #     cargo test --features vapoursynth

      # - name: With ffmpeg
      #   run: |
      #     cargo clippy --features ffmpeg,ffmpeg_build --tests --benches -- -D warnings
      #     cargo test --features ffmpeg,ffmpeg_build

      # - name: With all features
      #   run: |
      #     cargo clippy --features ffmpeg,ffmpeg_build,vapoursynth --tests --benches -- -D warnings
      #     cargo test --features ffmpeg,ffmpeg_build,vapoursynth
